#!/bin/bash

if [ $DOCKER_TAG == "arm64" ]
then
  docker build --plaform linux/arm64/v8 . -t ${IMAGE_NAME}
else
  if [ $DOCKER_TAG == "amd64" ]
  then
    docker build . -t ${IMAGE_NAME}
  else
    docker build . -t ${IMAGE_NAME}
  fi
fi