#!/bin/bash
# Setup docker to build for muliple targets

docker buildx create --name multibuilder --driver-opt network=host --use
docker buildx build --platform linux/arm64/v8,linux/amd64 -t ${IMAGE_NAME} .