on: [push]

jobs:
  chain_bench_scan_example:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Chain Bench
        id: chain-bench
        uses: aquasecurity/chain-bench-action@v1.0.0
        with:
          repository-url: ${{ github.server_url }}/${{ github.repository }} # Compiles to https://github.com/aquasecurity/chain-bench-action
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Attach JSON Results
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ steps.chain-bench.outputs.chain-bench-result }}
