name: Chain Bench

on: [push]

jobs:
  chain_bench_scan:
    runs-on: ubuntu-latest
    name: Repository Scan
    steps:
      - name: Chain Bench
        id: chain-bench
        uses: aquasecurity/chain-bench-action@v1.0.0
        with:
          repository-url: ${{ github.server_url }}/${{ github.repository }} # Compiles to https://github.com/aquasecurity/chain-bench-action
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Attach JSON Results
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: /tmp/report.json
